accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [


    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(),name ='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),

    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

book_bug_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
]

bookbug/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls'),),
    path('profiles/', include('profileapp.urls'), ),
    path('articles/', include('articleapp.urls'), ),
    path('comments/', include('commentapp.urls'),),
    path('projects/', include('projectapp.urls'), ),

              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name= 'create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns =[
     path('list/', ProjectListView.as_view(),name='list'),

     path('create/', ProjectCreateView.as_view(), name='create'),
     path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

homeapp/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body>

    {% include 'navbar.html' %}
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

homeapp/templates/footer.html
 <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 책벌레 테스트 메인페이지</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

homeapp/templates/head.html
 {% load static %}
<head>
    <title>BookBug</title>

      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>book-bug_test</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

        <!-- DEFAULT CSS LINK -->
        <link rel = "stylesheet" type="text/css" href="{% static 'base.css' %}">

  <script src="{% static 'js/scripts.js' %}"></script>
</head>

homeapp/templates/header.html
 <!-- Header-->
        <header style="background: rgba(162, 225, 42, 0.65);" class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">당신을 위한 BOOK</h1>
                    <p class="lead fw-normal text-black-50 mb-0">도서 전문 커넥팅 서비스</p>
                </div>
            </div>
        </header>

homeapp/templates/navbar.html
 <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'articleapp:list' %}" style="color: rgb(69, 101, 0);">책벌레</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-book-fill me-1"></i>
                            찜한 도서 개수
                            <span class="badge bg-dark text-white ms-1 rounded-pill">개수 표시 여기에</span>
                        </button>
                    </form>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'articleapp:list' %}">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">도서</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=2 %}">000 총류</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=3 %}">100 철학</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=4 %}">200 종교</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=5 %}">300 사회학</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=6 %}">400 자연과학</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=7 %}">500 기술과학</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=8 %}">600 예술</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=9 %}">700 언어</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=10 %}">800 문학</a></li>
                                <li><a class="dropdown-item" href="{% url 'projectapp:detail' pk=11 %}">900 역사</a></li>
                            </ul>
                        {% if not user.is_authenticated %}
                            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                                <span>login</span>
                            </a>
                            <a href="{% url 'accountapp:create' %}">
                                <span>회원가입</span>
                            </a>

                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ profile.writer.profile.nickname }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'accountapp:detail' pk=user.pk %}">내 책방</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">보관함</a></li>
                                <li><a class="dropdown-item" href="{% url 'profileapp:update' pk=user.pk %}">정보 수정</a></li>
                                <li><a class="dropdown-item" href="{% url 'accountapp:logout' %}">로그아웃</a></li>
                            </ul>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>