articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),

    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

book_bug_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
]

bookbug/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls'),),
    path('profiles/', include('profileapp.urls'), ),
    path('articles/', include('articleapp.urls'), ),
    path('comments/', include('commentapp.urls'),),
    path('projects/', include('projectapp.urls'), ),

              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns =[
     path('list/', ProjectListView.as_view(),name='list'),

     path('create/', ProjectCreateView.as_view(), name='create'),
     path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null= True)
    project = models.ForeignKey(Project, on_delete= models.SET_NULL, related_name='article',null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now=True, null= True)

projectapp/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    image = models.ImageField(upload_to='project/', null=False)
    title = models.CharField(max_length=20,null=False)

    descripition = models.CharField(max_length=200, null=True)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image', 'title', 'descripition']

projectapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(project= self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, **kwargs)


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project__list'
    template_name = 'projectapp/list.html'
    paginate_by =  25

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}

{% block content %}
  <div style="text-align: centers">
    <div>
      <h4>Create Project</h4>
    </div>
    <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}

      <input type="submit">
    </form>
  </div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      <img src="{{ target_project_image.url }}" alt="" style="height: 12rem; width: 12rem;">
    <h2>
      {{ target_project.title }}
    </h2>
      <h5>
        {{ target_project.description }}
      </h5>
    </div>

    <div>
      {% include 'snippets/list_fragment.html' with article_list=object_list %}

    </div>
  </div>

{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

.container {
    padding: 0;
    margin: 0 auto;
}

.container a {
    width: 45%;
    max-width: 250px;
}

.container div {
  width: 250px;
  height: 500px;
  background-color: antiquewhite;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 1rem;
}

.container img {
  width: 100%;
}
</style>
{% if article_list %}
<div class="container">

  {% for article in article_list %}
  <a href="{% url 'articleapp:detail' pk=article.pk %}">
      {% include 'snippets/card.html' with article=article %}
  </a>
  {% endfor %}
</div>

<script src="{% static 'js/magicgrid.js' %}"></script>

{% else %}
<div>
  <h1>no Articles YET!</h1>
</div>
{% endif %}

<div>
  <a href="{% url 'articleapp:create' %}">
    Create
  </a>
</div>

{% include 'snippets/pagination.html' with page_obj=page_obj %}
<div style ="text-align:center">
    <a href="{% url 'articleapp:create' %}">
        글쓰기
    </a>
</div>


{% endblock %}